# Generated by Django 2.2.1 on 2019-07-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('relation_type', models.CharField(max_length=5)),
                ('relation_subtype', models.CharField(max_length=5)),
                ('relation_link', models.CharField(blank=True, max_length=5)),
                ('relation_desc', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='relation_hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_relation', models.CharField(max_length=5)),
                ('l2_relation', models.CharField(max_length=5)),
                ('l3_relation', models.CharField(max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_hindi', models.CharField(max_length=100)),
                ('relation_english', models.CharField(max_length=100, unique=True)),
                ('relation_type', models.CharField(max_length=5)),
                ('relation_subtype', models.CharField(max_length=5)),
                ('relation_link', models.CharField(blank=True, max_length=5)),
                ('relation_desc', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bucketlist',
        ),
    ]
